package com.example.dagger2;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

public class MainActivity extends AppCompatActivity {
    private Car car;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

//       the DaggerCarComponent will be generated by dagger only after we build the project successfully
        CarComponent carComponent = DaggerCarComponent.create();

        car = carComponent.getCar();

        car.drive();


//        the code behind the DaggerCarComponent which is generated by the Dagger itself : -

    /*
    // Generated by Dagger (https://dagger.dev).
package com.example.dagger2;

import dagger.internal.DaggerGenerated;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DaggerCarComponent {
  private DaggerCarComponent() {
  }

  public static Builder builder() {
    return new Builder();
  }

  public static CarComponent create() {
    return new Builder().build();
  }

  public static final class Builder {
    private Builder() {
    }

    public CarComponent build() {
      return new CarComponentImpl();
    }
  }

  private static final class CarComponentImpl implements CarComponent {
    private final CarComponentImpl carComponentImpl = this;

    private CarComponentImpl() {


    }

    @Override
    public Car getCar() {
      return new Car(new Enigine(), new Wheels());
    }
  }
}

     */


    }

}